language: node_js
node_js:
- "stable"
# Cache our Gcloud SDK between commands
cache:
  directories:
  - "$HOME/google-cloud-sdk/"

before_install:
- openssl aes-256-cbc -K $encrypted_c1b660268e1f_key -iv $encrypted_c1b660268e1f_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- npm i -g yarn

install:
- yarn

script:
- yarn test

deploy:
  provider: gae
  keyfile: client-secret.json
  project: chunchumaru-163106

